---

- hosts: all
  become: true
  tasks:

  - name: Install apache2 package and php packages for Ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: true
    when: ansible_distribution == "Ubuntu"

  - name: Update repository index for CentOS
    ansible.builtin.dnf:
      update_cache: true
    when: ansible_distribution == "CentOS"

  - name: Install apache and php packages for CentOS
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
