---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache=yes

  - name: install open-vm-tools package
    apt:
      name: open-vm-tools
      state: latest
# This is just a comment
